version: '3'

services:
  turn-peer:
    entrypoint:
      - turn-client
      - peer
    depends_on:
      - turn-server
    links:
      - turn-server
    build:
      context: ../..
      dockerfile: "e2e/turn-client/Dockerfile"
      args:
        CI_GO_VERSION: latest
  turn-client:
    depends_on:
      - turn-server
      - turn-peer
    links:
      - turn-server
      - turn-peer
    build:
      context: ../..
      dockerfile: "e2e/turn-client/Dockerfile"
      args:
        CI_GO_VERSION: latest
  turn-server:
    build:
      context: .
      dockerfile: "server.Dockerfile"
networks:
  default:
    external:
      name: nat
