language: go

sudo: required

services:
  - docker

go:
  - 1.9.x
  - 1.10.x
  - master

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
 - go get -v -t .

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci -v -package .
 - cd integration-test && ./test.sh

matrix:
  allow_failures:
    - go: 'master'
  fast_finish: true
